### PR TITLE
Vagrant master provisioning commands

### PR DESCRIPTION
**Pull request by jakolehm**
```
$ kontena master vagrant
Usage:
    kontena master vagrant [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    create                        Create a new Vagrant master
    ssh                           SSH into Vagrant master
    start                         Start Vagrant master
    stop                          Stop Vagrant master
    restart                       Restart Vagrant master
    terminate                     Terminate Vagrant master
```

create:

```
$ kontena master vagrant create --help
Usage:
    kontena master vagrant create [OPTIONS]

Options:
    --memory MEMORY               How much memory node has (default: "512")
    --version VERSION             Define installed Kontena version (default: "latest")
    --auth-provider-url AUTH_PROVIDER_URL Define authentication provider url
    -h, --help                    print help

```

### CODE REVIEW

**Comment by jakolehm** [comment]
@miskun @nevalla ping

**Comment by miskun** [comment]
Maybe should mention how to use custom auth server in here?

**Comment by jakolehm** [comment]
`--auth-provider-url` option is now added

**Comment by nevalla** [comment]
Looks good!

**Pull request merged**
