### PR TITLE
Run post_start hooks before wait for port

### PR DESCRIPTION
**Pull request by jakolehm**
Regression in 1.3.

### CODE REVIEW

**Comment by SpComb** [comment]
Looks like a regression in 1.2 from #1607... the server used to wait for the agent `ServicePods::Creator` to run before doing the wait_for_port, and that included running the `post_start` hooks. 

The new code in 1.2 blocks the agent `ServicePods::Creator` on the wait_for_port before running the `post_start` hooks.

**Comment by jakolehm** [comment]
Ok, yes it seems that this buggy behaviour has been introduced in 1.2. I think we should fix this because it kinda harms some of the stacks that have post_start hooks (eg they initialize some files/settings that enable executable to open port).

**Comment by SpComb** [comment]
Just makes me wonder if there are also post-1.2 stacks where the `post_start` hooks rely on the service responding on the port... like `post_start: - cmd: curl http://localhost:8080/whatever`? :confused:

**Comment by SpComb** [comment]
The https://github.com/kontena/kontena/blob/master/docs/references/kontena-yml.md#hooks could also mention something about the order that `post_start` and `wait_for_port` run in.

**Comment by jakolehm** [comment]
@jnummelin improved docs. Should we include this into 1.3.3?

**Comment by jnummelin** [comment]
Docs look good to me 👍 

> Should we include this into 1.3.3?

Sure, why not :)

**Pull request merged**
