### PR TITLE
Added kontena-console command to master for local debugging

### PR DESCRIPTION
**Pull request by kke**
```
$ MONGODB_URI=mongodb://mongodb:27017/kontena_server bin/kontena_console

irb(main):001:0> Role.first
=> #<Role _id: 57ac1f8a699fb77ac1000006, created_at: 2016-08-11 06:47:38 UTC, updated_at: 2016-08-11 06:47:38 UTC, user_ids: nil, name: "master_admin", description: "Master admin">
```

### CODE REVIEW

**Comment by kke** [comment]
Implements #902

**Comment by jakolehm** [comment]
LGTM!

**Comment by SpComb** [comment]
The explicit `ENV["MONGODB_URI"]` overrides any `.env` and `config/mongoid.yml` configuration, so it's a little difficult to use in the development environment.

Won't the production Docker environment have an explicit `MONGODB_URI` configured anyways, so the default value here is a bit of a guess?

**Comment by kke** [comment]
With #1621 it should keep from crashing

Not sure about the path and command name.

It would be nice to do:
```
$ docker exec -it kontena-server-api console
# or
$ docker exec -it kontena-server-api kontena-console

```

instead of

```
$ docker exec -it kontena-server-api ./bin/kontena-console
```

Maybe we can put `app/bin/` to `$PATH`? Maybe use rake to start the console like the admin reset:

```
$ docker exec -it kontena-server-api rake kontena:console
```
 
@ping jakolehm

**Comment by jakolehm** [comment]
> Maybe we can put app/bin/ to $PATH?

Sounds good.

**Pull request merged**
