### PR TITLE
Update Weave Net to 1.8.2

### PR DESCRIPTION
**Pull request by jakolehm**
https://github.com/weaveworks/weave/releases/v1.8.2

### CODE REVIEW

**Comment by SpComb** [comment]
Need weave 1.8.3 to fix #1582

**Comment by jakolehm** [comment]
1.8.3 is not released yet.. imho we should take this in and do a separate PR for new updates.

**Comment by jnummelin** [comment]
Oh, somehow just by reading the related issue I had the wrong impression that 1.8.3 was already released. :/

Quickly tested locally and everything worked as expected.

So, LGTM

**Comment by SpComb** [comment]
Sure, not say we shouldn't update to 1.8.2 :) Haven't tested it yet, though

**Pull request merged**
