### PR TITLE
Add rbtrace support to server & agent

### PR DESCRIPTION
**Pull request by jakolehm**
Includes [rbtrace](https://github.com/tmm1/rbtrace) gem to server & agent that can be enabled with `RBTRACE` environment variable (disabled by default).

### CODE REVIEW

**Comment by jnummelin** [comment]
Is there much overhead in practice for enabling this always? The docs are bit vague:
> rbtrace is designed to have minimal overhead, and should be safe to run in production.

I'm just thinking if the actual overhead is minimal why not run it always?

**Comment by SpComb** [comment]
I wonder what the security implications of loading `rbttrace` are... what controls access to the traced process? I'm seeing some `msgget(rbtracer.mqi_key, 0666 | IPC_CREAT)` and a `/tmp/rbtrace-%d.sock`.

They'll be running with a Docker container though, so that will probably be enough to hide them away from any threat model.

**Comment by jakolehm** [comment]
Enabling this by default sounds a bit risky, we can change it later if we can prove that this does not have any side-effects.

**Comment by jnummelin** [comment]
I'm not sure if the GC tracing really works, tracing servers puma process with `rbtrace --pid 16 --gc` gives nothing out. :/ `16` process is both the leader and the only worker that has an agent connected at. The slow method tracing does work though, so `rbtrace` itself seems to be working.

**Comment by jnummelin** [comment]
Has anyone else tested the GC tracing, do I have PEBKAC issue?

**Comment by jnummelin** [comment]
@jakolehm @SpComb Have you tried the GC tracing with this, does it work?

**Comment by jakolehm** [comment]
Rebased.

@jnummelin haven't tried GC tracing.

**Pull request merged**
