### PR TITLE
Deploy stack by default on install/upgrade

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Comment by SpComb** [comment]
:+1: although this could also be linked to some issue on implementing a `kontena stack deploy --noop`, that shows what changed would be deployed on upgrade.

**Comment by kke** [comment]
(--noop = --dry-run)

**Comment by SpComb** [comment]
Docs need updating:

* https://github.com/kontena/kontena/blob/master/docs/getting-started/quick-start.md#step-4-deploy-your-first-application-stack

    > `$ kontena stack install --deploy kontena.yml`

* https://github.com/kontena/kontena/blob/master/docs/using-kontena/stacks.md#deploying-stacks

    > Use the --deploy flag to simultaneously deploy the stack services to the grid [...] If you omit the kontena stack install --deploy flag, then you must run kontena stack deploy wordpress-red separately.

**Comment by jakolehm** [comment]
Something is off here.. let's see if I can cleanup this with a new rebase.

**Pull request merged**
