### PR TITLE
Disable weave restart policy

### LINKED ISSUE #1249: Weave expose fails randomly on node reboot
Weave bridge creation is sometimes really slow and this causes expose to fail. 

Related: https://github.com/weaveworks/weave/issues/2479

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1249

### CODE REVIEW

**Comment by jakolehm** [comment]
@jnummelin @SpComb ping

**Comment by SpComb** [comment]
Hmm... I suppose this would be ideal, but testing the restart logic is a bit hairy.

Maybe the smaller `attach_router` change in #1251 would be simpler for 0.16.1, and then go for this + #1241 in 0.17?

**Comment by jakolehm** [comment]
I prefer this PR over #1251 because this is simpler and does not bring any new weave calls into the mix (are we really really sure that `attach-router` is ok to run).

**Comment by jakolehm** [comment]
Maybe we need to add backoff logic? This healing might be very resource intensive if weave does not want to stay alive (bad config etc). 

I'll look #1251 with fresh eyes and check if we can minimize the `attach-router` calls.

**Comment by jakolehm** [comment]
Is this a good idea anymore? Should we close?

**Comment by SpComb** [comment]
I think this ties into the broader theme of #1241 and the new `Kontena::Workers::ContainerStarterWorker`, maybe we should be doing something similar for all containers, not just weave?

None of the Docker restart-after-reboot policies really work, the only container that can actually do anything useful after a reboot is the `kontena-agent`. Having Docker start the etcd and kontena-ipam containers just leads to longer restart cycles once the agent does get everything up and running.

**Comment by jakolehm** [comment]
@jnummelin what do you think, close or continue?

**Comment by jnummelin** [comment]
I would close this and maybe (at some point) work on the broader restart-policy scope as @SpComb also mentions.

**Pull request closed without merging**
