### PR TITLE
Agent: use docker-api 1.32 Docker::Network#connect body_opts

### PR DESCRIPTION
**Pull request by SpComb**
Uses the new docker-api 1.32 `Docker::Network#connect` parameter `body_opts`: https://github.com/swipely/docker-api/commit/0c95907eaf9d1d6ac8ac3cbe10989450ddd6d57f

We don't need to monkey-patch `Docker::Network` anymore.

### CODE REVIEW

**Comment by SpComb** [comment]
Disclaimer: I have not actually tested this yet.

**Comment by jakolehm** [comment]
Travis is not happy

**Comment by jakolehm** [comment]
Docker-api has been already updated.

**Comment by SpComb** [comment]
The unnecessary `Docker::Network#connect` monkey-patching is still there https://github.com/kontena/kontena/blob/master/agent/lib/docker/network.rb

**Pull request closed without merging**
