### PR TITLE
Add provider labels to nodes after provisioning

### PR DESCRIPTION
**Pull request by kke**
Easier identification of node hosting provider when running across multiple cloud operators.

### CODE REVIEW

**Comment by jakolehm** [comment]
LGTM (but needs rebase)

**Comment by kke** [comment]
All your rebase are belong to us.

**Comment by jakolehm** [comment]
Something is off here.. @kke did you rebase or merge?

**Comment by kke** [comment]
Easier to make a new one. Closing this one.

**Pull request closed without merging**
