### PR TITLE
"kontena complete --subcommand-tree" prints out the full command tree for tests

### PR DESCRIPTION
**Pull request by kke**
For testing / completion purposes

### CODE REVIEW

**Comment by SpComb** [comment]
Could this be in spec form, re #2096

**Comment by SpComb** [comment]
Needs some CLI spec or test script that then loads each command in turn (with `--help` or something?) as a separate ruby process to verify that the `require`s work correctly.

**Comment by SpComb** [comment]
#### `bundle exec bin/kontena version --subcommand-tree | while read cmd; do bundle exec bin/$cmd --help > /dev/null && echo "ok: $cmd" || echo "failed: $cmd"; done`
```
[DEPRECATED] Use "kontena master user" instead
ok: kontena
ok: kontena cloud
ok: kontena cloud login
ok: kontena cloud logout
ok: kontena cloud master
ok: kontena cloud master list
ok: kontena cloud master add
ok: kontena cloud master remove
ok: kontena cloud master show
ok: kontena cloud master update
ok: kontena logout
ok: kontena grid
ok: kontena grid list
ok: kontena grid create
ok: kontena grid update
ok: kontena grid use
ok: kontena grid show
ok: kontena grid logs
ok: kontena grid remove
ok: kontena grid current
ok: kontena grid env
ok: kontena grid audit-log
ok: kontena grid user
ok: kontena grid user list
ok: kontena grid user add
ok: kontena grid user remove
ok: kontena grid cloud-config
ok: kontena grid trusted-subnet
ok: kontena grid trusted-subnet list
ok: kontena grid trusted-subnet add
ok: kontena grid trusted-subnet remove
ok: kontena grid health
ok: kontena app
ok: kontena app init
ok: kontena app build
ok: kontena app config
ok: kontena app deploy
ok: kontena app scale
ok: kontena app start
ok: kontena app stop
ok: kontena app restart
ok: kontena app show
ok: kontena app ps
ok: kontena app logs
ok: kontena app monitor
ok: kontena app remove
ok: kontena stack
ok: kontena stack install
ok: kontena stack ls
ok: kontena stack remove
ok: kontena stack show
ok: kontena stack upgrade
ok: kontena stack start
 [error] uninitialized constant Kontena::Cli::Helpers
         Rerun the command with environment DEBUG=true set to get the full exception
failed: kontena stack logs
ok: kontena stack monitor
ok: kontena stack build
ok: kontena stack reg
ok: kontena stack reg push
ok: kontena stack reg pull
ok: kontena stack reg search
ok: kontena stack reg show
ok: kontena stack reg remove
ok: kontena stack validate
ok: kontena service
ok: kontena service list
ok: kontena service create
ok: kontena service show
ok: kontena service update
ok: kontena service deploy
ok: kontena service stop
ok: kontena service start
ok: kontena service restart
ok: kontena service scale
ok: kontena service remove
ok: kontena service containers
ok: kontena service logs
ok: kontena service stats
ok: kontena service monitor
ok: kontena service env
ok: kontena service env list
ok: kontena service env add
ok: kontena service env remove
ok: kontena service secret
ok: kontena service secret link
ok: kontena service secret unlink
ok: kontena service link
ok: kontena service unlink
ok: kontena service exec
ok: kontena vault
ok: kontena vault list
ok: kontena vault write
ok: kontena vault read
ok: kontena vault update
ok: kontena vault remove
ok: kontena vault export
ok: kontena vault import
ok: kontena certificate
ok: kontena certificate register
ok: kontena certificate authorize
ok: kontena certificate get
ok: kontena node
ok: kontena node list
ok: kontena node show
ok: kontena node ssh
ok: kontena node update
ok: kontena node remove
ok: kontena node label
ok: kontena node label list
ok: kontena node label add
ok: kontena node label remove
ok: kontena node health
ok: kontena master
ok: kontena master list
ok: kontena master remove
ok: kontena master config
ok: kontena master config set
ok: kontena master config get
ok: kontena master config unset
ok: kontena master config load
ok: kontena master config dump
ok: kontena master use
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users invite
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users remove
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users list
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users role
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users role add
[DEPRECATED] Use "kontena master user" instead
ok: kontena master users role remove
ok: kontena master user
ok: kontena master user invite
ok: kontena master user remove
ok: kontena master user list
ok: kontena master user role
ok: kontena master user role add
ok: kontena master user role remove
ok: kontena master current
ok: kontena master login
 [error] uninitialized constant Kontena::Cli::Master
         Rerun the command with environment DEBUG=true set to get the full exception
failed: kontena master logout
ok: kontena master token
ok: kontena master token list
ok: kontena master token rm
ok: kontena master token show
ok: kontena master token current
ok: kontena master token create
ok: kontena master join
ok: kontena master audit-log
ok: kontena master init-cloud
ok: kontena master ssh
ok: kontena vpn
ok: kontena vpn create
ok: kontena vpn config
ok: kontena vpn remove
ok: kontena registry
ok: kontena registry create
ok: kontena registry remove
ok: kontena container
ok: kontena container list
ok: kontena container exec
ok: kontena container inspect
ok: kontena container logs
ok: kontena etcd
ok: kontena etcd get
ok: kontena etcd set
ok: kontena etcd mkdir
ok: kontena etcd list
ok: kontena etcd rm
ok: kontena etcd health
ok: kontena external-registry
ok: kontena external-registry add
ok: kontena external-registry list
ok: kontena external-registry remove
ok: kontena whoami
ok: kontena plugin
ok: kontena plugin list
ok: kontena plugin search
ok: kontena plugin install
ok: kontena plugin uninstall
ok: kontena version
ok: kontena volume
ok: kontena volume create
ok: kontena volume remove
ok: kontena volume list
ok: kontena hello
ok: kontena hello world
```

**Comment by kke** [comment]
Moved to `kontena complete --subcommand-tree`.

**Pull request merged**
