### PR TITLE
Improve travis automation

### PR DESCRIPTION
**Pull request by jakolehm**
- use bundler cache
- install mongodb stuff only when `$TEST_DIR=server`
- deploy gem & docker images on tags
  - if a pre-release, tag image also as `:edge`
 - if not a pre-release, tag with semver and `:latest`

travis

### CODE REVIEW

**Comment by jakolehm** [comment]
@kke @SpComb ping, should we merge?

**Comment by kke** [comment]
LGTM

**Comment by SpComb** [comment]
Unfortunately I really don't know enough about Travis to say.

**Comment by jakolehm** [comment]
Ok, let's do this...

**Comment by kke** [comment]
If it's broken, it's probably just going to break tests.
Wurst case scenario is that broken stuff gets deployed, but we should realize that soon enough.

**Pull request merged**
