### PR TITLE
Speed up CLI loading by reducing the number of explicitly loaded files

### PR DESCRIPTION
**Pull request by kke**
Before: (with #2334 and the plugin disabler from this PR)

```
$ time NO_PLUGINS=true bin/kontena whoami --help
0.26s user 0.06s system 92% cpu 0.342 total
```

After:
```
$ time NO_PLUGINS=true bin/kontena whoami --help
0.09s user 0.04s system 84% cpu 0.161 total
```

### CODE REVIEW

**Comment by jnummelin** [comment]
Needs rebase/merge

**Comment by jnummelin** [comment]
Lot of failing cli specs...

**Comment by kke** [comment]
Right. It now needs #2263

**Comment by jnummelin** [comment]
> Right. It now needs #2263

So this depends now on #2263 to be merged in first?

**Comment by jnummelin** [comment]
rebase/merge needed :)

**Comment by kke** [comment]
Snappy!

image

However, plugins are slooooow to load:
image

**Pull request merged**
