### PR TITLE
Use random initialization vector

### LINKED ISSUE #3183: Encrypted fields should use random iv
Currently all symmetrically encrypted fields use static iv. It would be better to switch to use random iv.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #3183

### CODE REVIEW

**Comment by SpComb** [comment]
Backwards compatibility considerations with existing vault secrets in the DB?

**Comment by jakolehm** [comment]
> Backwards compatibility considerations with existing vault secrets in the DB?

They seem to work just fine (tested manually).

**Comment by SpComb** [comment]
The `VAULT_IV` now gets ignored for any new deployments, and it only needed for backwards-compatibility with existing secrets... but the server still requires it to work?

We should support deployments without `VAULT_IV`, either making it optional, or adding migration to re-encrypt all the secrets and then just forgetting the `VAULT_IV`.

**Comment by SpComb** [comment]
The server [`Configuration`](https://github.com/kontena/kontena/blob/a099c4a238b0cc63498a323dcafeecdb48695e48/server/app/models/configuration.rb#L32)  model also uses `SymmetricEncryption.encrypt`, but it passes `true` for `random_iv`, so it's already using random IVs with the `@Enc` header.

**Comment by SpComb** [comment]
The server [`DigestHelper`](https://github.com/kontena/kontena/blob/a099c4a238b0cc63498a323dcafeecdb48695e48/server/app/helpers/digest_helper.rb#L26) is using `SymmetricEncryption.encrypt` without `random_iv: true`, but OTOH it looks like it's actually re-encrypting the value already encrypted by the `Configuration` model itself... so it probably doesn't really matter, it's just confusing.

```
irb(main):019:0> Configuration.find_by(key: 'server.salt').value['v']
=> "QEVu...D0m2...VGV\n"
irb(main):020:0> Configuration['server.salt']
=> "4Og...0Q=\n"
irb(main):021:0> AccessToken.salt
=> "$2a$10$nisf...gQe"
irb(main):022:0> SymmetricEncryption.decrypt('4Og...0Q=\n')
=> "$2a$10$nis...Qe"
```

**Comment by SpComb** [comment]
Testing shows that `symmetric-encrpytion` 3.x is indeed able to handle the existing ciphertexts that do not have any header and use a fixed IV: https://github.com/rocketjob/symmetric-encryption/blob/v3.9.1/lib/symmetric_encryption/symmetric_encryption.rb#L120-L126

This means that existing values without the `@Enc` header in mongo will get decrypted using the fixed `VAULT_IV`, and any new encrypted values will be stored with a random IV and the `@Enc` header. Testing with `kontena vault update test ...` before/after an upgrade:

```
> db.grid_secrets.find({"name": "test"})
{ "_id" : ObjectId("58e3c49cde35780bc6000000"), "name" : "test", "encrypted_value" : "dbGEfjVNCKDa2Jtwsq2N+w==\n", "grid_id" : ObjectId("580878e5de35781b2c000017"), "updated_at" : ISODate("2017-04-04T16:06:52.921Z"), "created_at" : ISODate("2017-04-04T16:06:52.921Z") }
> db.grid_secrets.find({"name": "test"})
{ "_id" : ObjectId("58e3c49cde35780bc6000000"), "name" : "test", "encrypted_value" : "QEVuQwBAEACAQvVtbI9Vk5YVmC8+rZGxRTRiwSBhDRvXazWJp6MV6g==\n", "grid_id" : ObjectId("580878e5de35781b2c000017"), "updated_at" : ISODate("2018-02-05T13:26:01.125Z"), "created_at" : ISODate("2017-04-04T16:06:52.921Z") }
```

```
irb(main):005:0> Base64.decode64("QEVuQwBAEACAQvVtbI9Vk5YVmC8+rZGxRTRiwSBhDRvXazWJp6MV6g==\n")
=> "@EnC\x00@\x10\x00\x80B\xF5ml\x8FU\x93\x96\x15\x98/>\xAD\x91\xB1E4b\xC1 a\r\e\xD7k5\x89\xA7\xA3\x15\xEA"
```

**Comment by SpComb** [comment]
It wouldn't hurt to have a migration to re-encrpyt all the encrypted values in mongo using a random IV, but that doesn't necessarily need to be part of this PR.

**Pull request merged**
