### PR TITLE
Fix error in StackDeployWorker when stack service has been removed

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Comment by SpComb** [comment]
Still seeing some errors when deploying a stack after removing a service from the stack file, it seems like there's a `GridServiceDeploy` with a nil `grid_service`?

## Before

Running git master, without this branch:

```
E, [2016-12-12T14:48:25.504355 #32129] ERROR -- StackDeployWorker: undefined method `worker' for #<Celluloid::CellProxy(StackDeployWorker:0x114b4a4)>
```

## After

```
127.0.0.1 - - [12/Dec/2016:14:49:44 +0200] "POST /v1/stacks/development/test/deploy HTTP/1.1" 200 142 0.0957
...
I, [2016-12-12T14:49:46.466250 #14775]  INFO -- GridServiceDeployer: starting to deploy development/test/test
I, [2016-12-12T14:49:46.496416 #14775]  INFO -- GridServiceDeployer: deploying service instance development/test/test-1 to node core-01
I, [2016-12-12T14:49:46.497350 #14775]  INFO -- GridServiceDeployer: throttling service instance development/test/test deploy because of min_health limit (1 instances in-progress)
I, [2016-12-12T14:50:10.553728 #14775]  INFO -- GridServiceDeployer: service development/test/test has been deployed
...
E, [2016-12-12T14:50:11.598958 #14775] ERROR -- : Actor crashed!
NoMethodError: undefined method `running?' for nil:NilClass
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:25:in `block in check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
	/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:23:in `with_lock'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:6:in `with_dlock'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:23:in `check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:12:in `block in watch'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `loop'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `watch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

### `GET /v1/stacks/development/test/deploys/584e9ce8de357839b7000000`

```
NoMethodError (undefined method `to_path' for nil:NilClass
Did you mean?  to_a):
  /home/kontena/kontena/kontena/server/app/views/v1/grid_service_deploys/_grid_service_deploy.json.jbuilder:5:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /home/kontena/kontena/kontena/server/app/views/v1/stack_deploys/_stack_deploy.json.jbuilder:6:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block (2 levels) in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `_map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:180:in `array!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `block in set!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `set!'
  /home/kontena/kontena/kontena/server/app/views/v1/stack_deploys/_stack_deploy.json.jbuilder:5:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /home/kontena/kontena/kontena/server/app/views/v1/stack_deploys/show.json.jbuilder:1:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/render.rb:216:in `render'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks/stack_deploys.rb:9:in `block (3 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks/stack_deploys.rb:5:in `block (2 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:376:in `get'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks/stack_deploys.rb:4:in `block in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `route'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks_api.rb:107:in `block (4 levels) in <class:StacksApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks_api.rb:106:in `block (3 levels) in <class:StacksApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:376:in `get'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks_api.rb:97:in `block (2 levels) in <class:StacksApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks_api.rb:74:in `block in <class:StacksApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:20:in `block (2 levels) in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:20:in `block in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/server.rb:52:in `block (2 levels) in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/server.rb:51:in `block in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/app/middlewares/token_authentication.rb:73:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:140:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:46:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

127.0.0.1 - - [12/Dec/2016:14:50:11 +0200] "GET /v1/stacks/development/test/deploys/584e9ce8de357839b7000000 HTTP/1.1" 500 35 0.1004
```

**Comment by SpComb** [comment]
Also this, unrelated but noticed it at the same time:

```
E, [2016-12-12T15:00:11.746925 #14775] ERROR -- StackDeployWorker: undefined method `warning' for #<Celluloid::CellProxy(StackDeployWorker:0x2723a88)>
Did you mean?  warn
```

**Comment by jakolehm** [comment]
@SpComb fixed that warning

**Comment by SpComb** [comment]
> @SpComb fixed that warning

LGTM on that part

```
W, [2016-12-12T15:12:48.672903 #15984]  WARN -- StackDeployWorker: waiting for deploy of development/test/test2 to finish timed out
```

**Comment by jakolehm** [comment]
@SpComb how did you manage to get those other errors? Did you have a deploy running while you updated & deployed stack?

**Comment by SpComb** [comment]
Just using `kontena stack upgrade --deploy` to swap between these two stacks:

```yaml
stack: terom/test
version: 0.0.1
services:
    test:
        image: debian:jessie
        command: echo test
```

```yaml
stack: terom/test
version: 0.0.1
services:
    test:
        image: debian:jessie
        command: echo test
    test2:
        image: debian:jessie
        command: echo test2
```

The down-servicing deploy fails immediately after deploying the first `test` service succeeds, as if it were trying to deploy the removed `test2` service.

**Comment by SpComb** [comment]
A little bit of debugging shows that `StackDeployWorker` actually calls `deploy_service` on the removed service.

```
127.0.0.1 - - [12/Dec/2016:15:35:19 +0200] "PUT /v1/stacks/development/test HTTP/1.1" 200 1931 0.1019
D, [2016-12-12T15:35:19.572208 #17406] DEBUG -- TokenAuthentication: Access token found
127.0.0.1 - - [12/Dec/2016:15:35:19 +0200] "POST /v1/stacks/development/test/deploy HTTP/1.1" 200 142 0.0823
D, [2016-12-12T15:35:19.657356 #17406] DEBUG -- TokenAuthentication: Access token found
D, [2016-12-12T15:35:19.672344 #17406] DEBUG -- GridServiceRemoveWorker: remove_grid_service test2...
127.0.0.1 - - [12/Dec/2016:15:35:19 +0200] "GET /v1/stacks/development/test/deploys/584ea797de357843fe00000e HTTP/1.1" 200 142 0.0879
D, [2016-12-12T15:35:20.775686 #17406] DEBUG -- TokenAuthentication: Access token found
D, [2016-12-12T15:35:20.776271 #17406] DEBUG -- GridServiceRemoveWorker: remove_grid_service: test2
D, [2016-12-12T15:35:20.781800 #17406] DEBUG -- StackDeployWorker: deploy_service test...
127.0.0.1 - - [12/Dec/2016:15:35:20 +0200] "GET /v1/stacks/development/test/deploys/584ea797de357843fe00000e HTTP/1.1" 200 321 0.1103
I, [2016-12-12T15:35:20.860324 #17406]  INFO -- GridServiceDeployer: starting to deploy development/test/test
I, [2016-12-12T15:35:20.891514 #17406]  INFO -- GridServiceDeployer: deploying service instance development/test/test-1 to node core-01
I, [2016-12-12T15:35:20.892018 #17406]  INFO -- GridServiceDeployer: throttling service instance development/test/test deploy because of min_health limit (1 instances in-progress)
D, [2016-12-12T15:35:21.886427 #17406] DEBUG -- TokenAuthentication: Access token found
127.0.0.1 - - [12/Dec/2016:15:35:21 +0200] "GET /v1/stacks/development/test/deploys/584ea797de357843fe00000e HTTP/1.1" 200 348 0.1031
D, [2016-12-12T15:35:22.972882 #17406] DEBUG -- TokenAuthentication: Access token found
127.0.0.1 - - [12/Dec/2016:15:35:22 +0200] "GET /v1/stacks/development/test/deploys/584ea797de357843fe00000e HTTP/1.1" 200 348 0.0864
D, [2016-12-12T15:35:24.076649 #17406] DEBUG -- TokenAuthentication: Access token found
127.0.0.1 - - [12/Dec/2016:15:35:24 +0200] "GET /v1/stacks/development/test/deploys/584ea797de357843fe00000e HTTP/1.1" 200 348 0.1008
I, [2016-12-12T15:35:24.188528 #17406]  INFO -- GridServiceDeployer: service development/test/test has been deployed
I, [2016-12-12T15:35:24.620800 #17406]  INFO -- LeaderElectorJob: won election ♚
D, [2016-12-12T15:35:24.804710 #17406] DEBUG -- StackDeployWorker: deploy_service: test
D, [2016-12-12T15:35:24.807340 #17406] DEBUG -- StackDeployWorker: deploy_service test2...
E, [2016-12-12T15:35:24.921539 #17406] ERROR -- : Actor crashed!
NoMethodError: undefined method `running?' for nil:NilClass
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:25:in `block in check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
	/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:23:in `with_lock'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:6:in `with_dlock'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:23:in `check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:12:in `block in watch'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `loop'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `watch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by jakolehm** [comment]
@SpComb reproduced the error and fixed the bug.

**Pull request merged**
