### PR TITLE
docs (deploy) Container affinity.

### LINKED ISSUE #1402: container affinity
Currently there is `service` affinity like:

```
affinity:
  - service==mysql
```

But there are some (raw docker) cases when one would like to schedule a service in the same machine as where a container is running (see https://github.com/jeroenpeeters/docker-ssh)

Affinity setting `container==mysql-1` would ensure this.

### PR DESCRIPTION
**Pull request by matti**
Fixes #1402

### CODE REVIEW

**Comment by jakolehm** [comment]
Imho container affinity is a power-user feature and we should note that in the docs.. I'm a bit against the whole idea of container affinity because it exposes too much internals.

**Comment by matti** [comment]
Not really sure. I want to deploy a service that uses the same docker daemon (https://github.com/jeroenpeeters/docker-ssh) and this is very handy. Not sure how this differs from any other affinities.

**Comment by jakolehm** [comment]
Because we reserve right to change container naming ;) (reason why it should be used with care). I think it would be make more sense to have "service instance" affinity.

**Comment by matti** [comment]
So still no docs on container affinity.

**Pull request merged**
