### PR TITLE
[WIP] Omnibus package for Windows

### LINKED ISSUE #2307: Missing CLI omnibus installer for Windows
The [CLI Omnibus](https://github.com/kontena/kontena/tree/master/cli/omnibus) package is currently only built for OS X.

There should also be a Windows build/installer.

### PR DESCRIPTION
**Pull request by jakolehm**
- upgrade ruby version to 2.4.1
- upgrade readline & nokogiri to work with ruby 2.4.1
- msi package config

Fixes #2307

### CODE REVIEW

**Comment by SpComb** [comment]
Needs merge with #2656

This is a blocker for the 1.4 release.

**Comment by jakolehm** [comment]
It seems that we cannot get this to work in time for 1.4. We probably need to document cli installation on Windows better:
- use Linux Subsystem for Windows
- install Ruby & Devkit

**Comment by colinmollenhour** [comment]
WSL with Ubuntu Ruby packages works great for me. Personally I use a Linux VM for running docker daemon and using DOCKER_HOST pointed at the VM I can easily do `kontena build` from the WSL now instead of inside the VM. The only issue I have is there are warnings about my PATH containing locations from other filesystems.  To quash those warnings I added this to `.profile`:

    export PATH=${PATH%%:/mnt/*}

**Comment by SpComb** [comment]
Status? Should this PR be updated, or closed because we're not planning on setting up windows build hosts?

**Comment by jakolehm** [comment]
We tried to setup windows build hosts but getting working builds seems to be very hard. We can probably close this for now (or leave it open for 1.5).

**Comment by SpComb** [comment]
Were the problems with the actual `omnibus build`, or with getting the CI automation setup? This PR could still be useful if it let you do manual omnibus builds.

**Comment by jakolehm** [comment]
Problems were with `omnibus build`. Not sure if they were related to Windows Server but the actual build environment is very tricky to setup for Windows.

**Comment by SpComb** [comment]
Out of date and not going anywhere.

**Pull request closed without merging**
