### PR TITLE
AWS node provision

### PR DESCRIPTION
**Pull request by nevalla**
This PR implements node provision to AWS.

**kontena node aws create**
```
Usage:
    kontena node aws create [OPTIONS]

Options:
    --name NAME                   Node name
    --access-key ACCESS_KEY       AWS access key ID
    --secret-key SECRET_KEY       AWS secret key
    --region REGION               EC2 Region (default: "eu-west-1")
    --zone ZONE                   EC2 Availability Zone (default: "a")
    --vpc-id VPC ID               Virtual Private Cloud (VPC) ID
    --subnet-id SUBNET ID         VPC option to specify subnet to launch instance into
    --key-pair KEY_PAIR           EC2 Key Pair
    --type SIZE                   Instance type (default: "t2.small")
    --storage STORAGE             Storage size (GiB) (default: "30")
    --version VERSION             Define installed Kontena version (default: "latest")
    -h, --help                    print help
```

**kontena node aws terminate**

```
Usage:
    kontena node aws terminate [OPTIONS] NAME

Parameters:
    NAME                          Node name

Options:
    --access-key ACCESS_KEY       AWS access key ID
    --secret-key SECRET_KEY       AWS secret key
    --region REGION               EC2 Region
    -h, --help                    print help
``` 

**kontena node aws restart**

```
Usage:
    kontena node aws restart [OPTIONS] NAME

Parameters:
    NAME                          Node name

Options:
    --access-key ACCESS_KEY       AWS access key ID
    --secret-key SECRET_KEY       AWS secret key
    --region REGION               EC2 Region
    -h, --help                    print help
```

### CODE REVIEW

**Comment by jakolehm** [comment]
Looks really nice!

**Comment by jakolehm** [comment]
Just wondering.... does it always select "default" vpc id? It would be better if user could set it manually.

**Comment by miskun** [comment]
Looking at the usage, I think we could change:

```
kontena node aws create [OPTIONS]
```

to

```
kontena node aws create [OPTIONS] NAME
```

Just to make it consistent with rest of the commands. What do you think?

**Comment by jakolehm** [comment]
Create command name parameter discussion has been moved to separate issue because it affects also other provisioners:  https://github.com/kontena/kontena/issues/157

**Comment by nevalla** [comment]
@jakolehm @miskun ping

**Comment by nevalla** [comment]
@jakolehm @miskun can we merge this?

**Comment by jakolehm** [comment]
Yes please

**Pull request merged**
