### PR TITLE
Add retriable for retrying hooks during deploy

### PR DESCRIPTION
**Pull request by kke**

### CODE REVIEW

**Comment by jakolehm** [comment]
Why we need to retry hooks?

**Comment by kke** [comment]
Robustness.

During testing I encountered a situation where the first step of auth provider config passed and the second one gave some weird timeout error and so the rest of the steps were not run since one of them raised.

Of course it would be possible to just retry X times using plain rescue.

**Comment by jakolehm** [comment]
Ok, just thought if there are any side-effects. It seems that retrying these hooks is safe.

**Comment by jakolehm** [comment]
Rebase, pls.

**Comment by jakolehm** [comment]
LGTM

**Pull request merged**
