### PR TITLE
DigitalOcean node provisioner

### PR DESCRIPTION
**Pull request by jakolehm**
This PR provides cli helper commands to provision droplets to DigitalOcean that are automatically provisioned and joined to Kontena grid as nodes.

```sh
$ kontena node provision digitalocean --token=<do_token> --ssh-key=<path_to_ssh_public_key>

$ kontena node destroy digitalocean --token=<do_token> --name=<node_name>
```

### CODE REVIEW

**Comment by miskun** [comment]
we should still consider those verbs; i'd prefer:
* provision --> **add** (or add, create, deploy)
* destroy --> **remove** (or delete, terminate)

"destroy" is just seems too scary :) "add" is easy to remember.

**Comment by jakolehm** [comment]
We already have `node remove`, it removes node from the grid but does not destroy the server. That's why I thought that scary `destroy` would be better because it will eat your server (and data)?

**Comment by miskun** [comment]
Ok, I see. What does node remove actually do? I think it should be considered as "kick"; so basically revoking access token for a node. But this might require heave redesign of node "join" process and workflows...

**Comment by jakolehm** [comment]
We have only grid tokens atm so we cannot revoke node access token. So current `node remove` command is handy when you shutdown/terminate node via some other tool and want it to disappear from `node list` immediately.

**Pull request closed without merging**
