### PR TITLE
CLI: Removed the app subcommand, it is now available as a plugin

### LINKED ISSUE #2597: Move app commands to plugin

### PR DESCRIPTION
**Pull request by kke**
Fixes #2597

The `kontena app` subcommand has been removed in favour of Kontena Stacks.

The old subcommand can still be used by installing the `app-command` plugin by using:

```
$ kontena plugin install app-command
```

To test this, you can add something like this to Gemfile:

```ruby
gem 'kontena-plugin-app-command', github: 'kontena/kontena-plugin-app-command'
```

run `bundle` and then `bundle exec ruby bin/kontena app xxxx`

### CODE REVIEW

**Comment by SpComb** [comment]
The [`kontena-plugin-app-command`](https://rubygems.org/gems/kontena-plugin-app-command) should proabably have a non-pre release before the final 1.4.0 for `kontena plugin install` to work without `--pre`?

**Comment by kke** [comment]
Yep, that was the idea.

**Comment by SpComb** [comment]
The e2e tests include some specs for the `app` commands, I think we should still keep those, and either have them use `kontena plugin install app-command`, or add the `kontena-plugin-app-command` to the `test/Gemfile`?

**Comment by kke** [comment]
Sounds like a good idea

**Comment by kke** [comment]
> Release the plugin so that kontena plugin install works (or make a separate issue for this so that we don't forget to do that before the 1.4 release)

It's out

> Fix the e2e app specs by installing the plugin

Done, but it has to use the pre version of plugin, because non-pre requires 1.4.0 (and we are still at .pre*)

**Comment by SpComb** [comment]
e2e specs pass

```

app subcommand
  with the app-command plugin
    app deploy
 [done] Creating redis      
 [done] Creating lb      
 [done] Creating nginx      
 [done] Deploying redis      
⊛ Deployed instance e2e/null/simple-redis-1 to node localhost
 [done] Deploying lb      
⊛ Deployed instance e2e/null/simple-lb-1 to node localhost
 [done] Deploying nginx      
⊛ Deployed instance e2e/null/simple-nginx-1 to node localhost
NAME             INSTANCES   STATEFUL   STATE     EXPOSED PORTS
⊝ simple-nginx   1 / 1       no         running
⊝ simple-lb      1 / 1       no         running   0.0.0.0:80->80/tcp
⊝ simple-redis   1 / 1       no         running
 [done] removing nginx     
 [done] removing redis     
 [done] removing lb     
      deploys a simple app

app subcommand
  with the app-command plugin
    app ps
NAME                           IMAGE                                              INSTANCES       STATEFUL   STATE           PORTS                                             
redis                          -                                                  -               -          -               -                                                 
nginx                          -                                                  -               -          -               -                                                 
lb                             -                                                  -               -          -               -                                                 
NAME                           IMAGE                                              INSTANCES       STATEFUL   STATE           PORTS                                             
redis                          -                                                  -               -          -               -                                                 
nginx                          -                                                  -               -          -               -                                                 
lb                             -                                                  -               -          -               -                                                 
      returns list

app subcommand
  with the app-command plugin
    app remove
 [done] Creating redis      
 [done] Creating lb      
 [done] Creating nginx      
 [done] Deploying redis      
⊛ Deployed instance e2e/null/simple-redis-1 to node localhost
 [done] Deploying lb      
⊛ Deployed instance e2e/null/simple-lb-1 to node localhost
 [done] Deploying nginx      
⊛ Deployed instance e2e/null/simple-nginx-1 to node localhost
 [done] removing nginx     
 [done] removing redis     
 [done] removing lb     
NAME  INSTANCES  STATEFUL  STATE  PORTS
      removes a deployed app

Finished in 1 minute 31.74 seconds (files took 0.24474 seconds to load)
3 examples, 0 failures
```

**Pull request merged**
