### PR TITLE
Allow docker-engine 1.12 in ubuntu packages

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Comment by jakolehm** [comment]
@SpComb ping

**Comment by SpComb** [comment]
Basic install and agent / host node works fine, is there something specific to test, like cadvisor stats?

```
docker-engine:
  Installed: 1.12.2-0~xenial
  Candidate: 1.12.2-0~xenial
  Version table:
 *** 1.12.2-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.12.1-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
     1.12.0-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
     1.11.2-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
     1.11.1-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
     1.11.0-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
kontena-server:
  Installed: 0.16.0.dev-1
  Candidate: 0.16.0.dev-1
  Version table:
 *** 0.16.0.dev-1 100
        100 /var/lib/dpkg/status
kontena-agent:
  Installed: 0.16.0.dev-1
  Candidate: 0.16.0.dev-1
  Version table:
 *** 0.16.0.dev-1 100
        100 /var/lib/dpkg/status
```

I would show the updated Docker version in the node info, but  #1170 ^^

`kontena node show terom-xenial-test`
```
terom-xenial-test:
  id: CFVO:GEKH:3OJU:IV7H:G75V:DPG7:F6BF:MJN7:KL5E:TS46:BMNF:VY7W
  agent version: 0.16.0.dev
  connected: yes
  last connect: 2016-10-20T11:27:30.739Z
  last seen: 2016-10-20T11:30:38.197Z
  public ip: 146.185.146.38
  private ip: 146.185.146.38
  overlay ip: 10.81.0.1
  os: Ubuntu 16.04.1 LTS
  driver: devicemapper
  kernel: 4.4.0-38-generic
  initial node: yes
  labels:
  stats:
    cpus: 1
    load: 0.42 0.51 0.29
    memory: 0.41 of 0.97 GB
    filesystem:
      - /var/lib/docker: 0.1 of 9.99 GB
```

**Comment by jakolehm** [comment]
cadvisor works with 1.12, tested on other systems.

**Comment by SpComb** [comment]
Basic service stats works:

`kontena service create redis redis`
`kontena service start redis`
`kontena service stats redis`
```
CONTAINER                      CPU %           MEM USAGE/LIMIT      MEM %           NET I/O        
redis-1                        0.17%           10.95M / N/A         N/A             648B/690B      
```

**Comment by SpComb** [comment]
One minor difference in the packaging going from Docker 1.11 -> Docker 1.12 is the new `/usr/bin/dockerd` binary.

`docker-engine=1.12` ships with `ExecStart=/usr/bin/dockerd -H fd://`, whereas `docker-engine=1.11` ships with `ExecStart=/usr/bin/docker daemon -H fd://`.

Our package overrides those to use `ExecStart=/usr/bin/docker daemon -H fd:// ${DOCKER_OPTS}` which should be fine for both, I guess.

**Pull request merged**
