### PR TITLE
Allow to set a grid token manually

### PR DESCRIPTION
**Pull request by kke**
Implements #1045

```
$ kontena grid create --grid-token abcd1234 testing
```

### CODE REVIEW

**Comment by jakolehm** [comment]
Looks good! But I would change the option name to just `--token`.

**Comment by matti** [comment]
Yep, like the --force-deploy in deploy was changed to --force (main command was deploy, here grid)

**Comment by kke** [comment]
Changed

**Comment by jakolehm** [comment]
@kke needs rebase

**Pull request merged**
