### PR TITLE
Default to fullchain certificate with options for cert only or chain

### PR DESCRIPTION
**Pull request by jnummelin**
This PR changes certificate management to default to using fullchain certificates as plain certs of LE are not overly trusted with all client libraries. (some rubies, docker, wget, ...). Also adds cli options to get either chain, fullchain or plain cert.

### CODE REVIEW

**Comment by matti** [comment]
#943

**Comment by nevalla** [comment]
Looks good!

**Comment by jakolehm** [comment]
@jnummelin tagged this to 0.15.1, is it ok? .. and should we add documentation for this new option?

**Comment by jnummelin** [comment]
version is ok. I'll add some docs for the options.

**Comment by jnummelin** [comment]
docs updated

**Pull request merged**
