### PR TITLE
Render only working service links

### LINKED ISSUE #1766: Cannot remove grid XYZ
Hello -
I want to delete my kontena grid using **"kontena grid remove --force testing"**. In order to do it properly I removed each node in this grid and stopped the kontena-agent service on them.  **"kontena node ls"** shows zero nodes, so I can start to delete my grid.

```sh
foo@bar:~$ kontena node ls
Name                                                                   Status     Initial    Labels                                  
foo@bar:~$ kontena service ls
 [error] Internal Server Error
foo@bar:~$ kontena grid remove --force testing
 [fail] removing testing grid      
 [error] {"grid"=>"Grid has services"}
foo@bar:~$ 
``` 

Is there any config file/ folder of kontena which define the services? Or is there another way to solve it.

Best regards,

vinhmmkh

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1766

### CODE REVIEW

**Comment by SpComb** [comment]
Not sure it makes sense to add code cruft to every possible place that might be nil in the case of what's essentially database corruption?

We should fix the code to not leave dangling references... like a `before_destroy` hook on the `GridService` or such?

**Comment by jakolehm** [comment]
Yes, we could probably use mongo `pull` to remove item from links when service is destroyed.

**Comment by SpComb** [comment]
:-1: on this in favor of a fix for #1769 

That might be a mongoid hook that raises an error if anything tries to removed a linked-to service, in addition to a `Stacks::Update` mutation validation for the same?

**Comment by SpComb** [comment]
Superseded by #1873

**Pull request closed without merging**
