### PR TITLE
Grid cloud-config sub-command

### LINKED ISSUE #461: Generate `cloud-config.yaml` for a Grid from Kontena CLI
There are hundreds of platforms Kontena may be installed. In most cases, we can use cloud-config.yaml. The proposed solution: add `kontena grid cloud-confing` command that will generate the cloud-config file for a grid.

Will fix #367

### PR DESCRIPTION
**Pull request by jakolehm**
```
$ kontena grid cloud-config -h
Usage:
    kontena grid cloud-config [OPTIONS] NAME

Parameters:
    NAME                          Grid name

Options:
    --dns DNS                     DNS server
    --peer-interface IFACE        Peer (private) network interface (default: "eth1")
    --docker-bip BIP              Docker bridge ip (default: "172.17.43.1/16")
    --version VERSION             Agent version (default: "latest")
```

Fixes #461

### CODE REVIEW

**Comment by jakolehm** [comment]
@faddat, this should fix bare-metal provision needs ( #367 ).

**Comment by jakolehm** [comment]
@nevalla ping

**Comment by faddat** [comment]
:D

**Comment by nevalla** [comment]
Looks good!

**Comment by faddat** [comment]
so, I'll keep my end of the deal-- time to get this whizzing along with pixiecore :)!

**Comment by faddat** [comment]
Thanks guys, sorry to get back so slowly.... Duty called and what have you.  I now want to do a reinvestigation of kontena.

**Pull request merged**
