### PR TITLE
Update to dry-validation 0.8.0

### LINKED ISSUE #824: Can't install gem kontena-cli
```
$ sudo gem install kontena-cli
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: kontena-cli requires dry-logic (= 0.2.2); dry-validation requires dry-logic (>= 0.2.2, ~> 0.2); dry-types requires dry-logic (>= 0.2.3, ~> 0.2)
```

Why you are using very strong dependencies rules?

### PR DESCRIPTION
**Pull request by solnic**
I haven't updated all rules to the new syntax, but basically in places where you have blocks w/o disjunctions you can just do `value(:some_predicate?)` and when it must be filled use `filled(:some_predicate?)` and when it can be nil do `maybe(:some_predicate?)`

Fixes #824

### CODE REVIEW

**Comment by solnic** [comment]
one more thing - rubygems is having some issues with index caching, so it doesn't see latest dry-logic when bundling, it works with `--full-index` option but it's of course dead slow to bundle like that.

**Comment by nevalla** [comment]
Awesome! Thanks!

**Comment by nevalla** [comment]
Rubygems dependency cache issues seems to be fixed now \o/. @solnic could you rebase and resolve conflicts in Gemfile? We had to made patch release yesterday with hard dependencies. Also could you sign the CLA, we'll love to include this in our next release.

**Comment by solnic** [comment]
@nevalla cla signed, branch rebased, the build's green 🎉

**Comment by jakolehm** [comment]
LGTM!

**Pull request merged**
