### PR TITLE
Fix Ubuntu xenial resolvconf

### PR DESCRIPTION
**Pull request by SpComb**
This fixes a regression from the existing Ubuntu packages where the Ubuntu xenial host nodes cannot resolve the `.kontena.local` DNS names.

* Rename `/opt/kontena` to replace previous `/opt/bin`

    Matches the `/opt/kontena/bin/cadvisor` used by the `kontena-cadvisor` container.

* Do not mark the `/opt/kontena/kontena-*.sh` scripts as conffiles

* Use a resolvconf helper script to register the `docker0` gateway address as a resolvconf nameserver

    Uses systemd service unit `ExecStartPost` / `ExecStopPost` within the `kontena-agent.service`:

    ```
ExecStartPost=/opt/kontena/kontena-resolvconf.sh start
ExecStopPost=/opt/kontena/kontena-resolvconf.sh stop
    ```

    Uses the `lo.kontena-docker` name to sort the nameserver higher than any `ethX.*` entry from dhclient.

## Testing

`cat /etc/resolv.conf `
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
```
`systemctl start kontena-agent`
`cat /etc/resolv.conf `
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.17.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4
```
`getent hosts redis`
```
10.81.1.11      redis
10.81.1.9       redis
10.81.1.5       redis
10.81.1.3       redis
10.81.1.8       redis
10.81.1.4       redis
10.81.1.7       redis
10.81.1.6       redis
10.81.1.1       redis
10.81.1.10      redis
```
`systemctl stop kontena-agent`
`cat /etc/resolv.conf`
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
```

`journalctl -u kontena-agent.service`
```
Oct 24 13:26:25 terom-xenial-node1 systemd[1]: Starting Kontena Agent...
Oct 24 13:26:25 terom-xenial-node1 docker[22288]: kontena-agent
Oct 24 13:26:25 terom-xenial-node1 docker[22293]: kontena-agent
Oct 24 13:26:25 terom-xenial-node1 kontena-resolvconf.sh[22301]: Adding resolvconf lo.kontena-docker: nameserver=172.17.0.1
Oct 24 13:26:25 terom-xenial-node1 systemd[1]: Started Kontena Agent.
Oct 24 13:26:26 terom-xenial-node1 docker[22300]: /app/lib/docker/version.rb:3: warning: already initialized constant Docker::API_VERSION
Oct 24 13:26:26 terom-xenial-node1 docker[22300]: /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/version.rb:6: warning: previous definition of API_VERSION was here
Oct 24 13:26:26 terom-xenial-node1 docker[22300]: I, [2016-10-24T13:26:26.224206 #1]  INFO -- Kontena::Agent: initializing agent (version 0.16.0.dev9)
...
Oct 24 13:26:42 terom-xenial-node1 systemd[1]: Stopping Kontena Agent...
Oct 24 13:26:42 terom-xenial-node1 docker[22300]: I, [2016-10-24T13:26:42.941703 #1]  INFO -- Kontena::Agent: Got signal TERM
Oct 24 13:26:42 terom-xenial-node1 docker[22300]: I, [2016-10-24T13:26:42.942133 #1]  INFO -- Kontena::Agent: Shutting down...
Oct 24 13:26:42 terom-xenial-node1 docker[22300]: I, [2016-10-24T13:26:42.949047 #1]  INFO -- Kontena::Workers::QueueWorker: stopped processing of msg queue
Oct 24 13:26:42 terom-xenial-node1 docker[22300]: I, [2016-10-24T13:26:42.951626 #1]  INFO -- Kontena::Workers::LogWorker: stopped log streaming
Oct 24 13:26:42 terom-xenial-node1 docker[22300]: I, [2016-10-24T13:26:42.952633 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
Oct 24 13:26:43 terom-xenial-node1 docker[23188]: kontena-agent
Oct 24 13:26:43 terom-xenial-node1 kontena-resolvconf.sh[23204]: Deleting resolvconf lo.kontena-docker
Oct 24 13:26:43 terom-xenial-node1 systemd[1]: Stopped Kontena Agent.

### CODE REVIEW

**Comment by jakolehm** [comment]
Looks good!

**Comment by SpComb** [comment]
This fixes a regression from the existing Ubuntu packages where the Ubuntu xenial host nodes cannot resolve the `.kontena.local` DNS names.

OTOH I'm not entirely sure if we should deconfigure the resolver when stopping the `kontena-agent` service. Stopping the agent itself still leaves weave around.

**Comment by jnummelin** [comment]
IMO we should not deconfigure resolver when agent is stopped. Weave and all running services will continue to run so it would be not logical that the name resolving would stop to work.

**Comment by SpComb** [comment]
Updated to preserve resolvconf on `kontena-agent.service` stop, and clear it on package removal.

`cat /etc/resolv.conf `
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.17.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4
```
`ping redis`
```
PING redis (10.81.1.11) 56(84) bytes of data.
64 bytes from redis-10.kontena.local (10.81.1.11): icmp_seq=1 ttl=64 time=0.252 ms
^C
--- redis ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.252/0.252/0.252/0.000 ms
```
`systemctl stop kontena-agent`
`ping redis-10`
```
PING redis-10 (10.81.1.11) 56(84) bytes of data.
64 bytes from redis-10.kontena.local (10.81.1.11): icmp_seq=1 ttl=64 time=0.102 ms
Progress: [ 25%] [############...................................] 4 time=0.154 ms
64 bytes from redis-10.kontena.local (10.81.1.11): icmp_seq=3 ttl=64 time=0.118 ms
^C
--- redis-10 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.102/0.124/0.154/0.025 ms
```
`apt remove kontena-agent`
```
...
Removing kontena-agent (0.16.0.dev9-1) ...
Deleting resolvconf lo.kontena-docker
Removed symlink /etc/systemd/system/multi-user.target.wants/kontena-agent.service.
```
`cat /etc/resolv.conf`
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Pull request merged**
