### PR TITLE
Release 1.3.1

### PR DESCRIPTION
**Pull request by kke**

### CODE REVIEW

**Comment by SpComb** [comment]
PR title and branch name is kinda wrong if it's an rc release

**Comment by kke** [comment]
The tag points to a valid commit, once the rc branches are deleted (as done before), it makes no difference. (tags do not relate to branches)

**Comment by SpComb** [comment]
e2e specs pass, apart from a flaky `stack install from file installs stack` spec, and `plugin support` issues related to the old `kommando` version in `test/Gemfile.lock`.

**Comment by SpComb** [comment]
Tested rc2 to fix #2484 oauth2 API issues.

**Pull request merged**
