### PR TITLE
Release 1.2.1.rc1

### PR DESCRIPTION
**Pull request by SpComb**
* [Changelog](https://github.com/kontena/kontena/blob/release/v1.2.1.rc1/CHANGELOG.md)
* [v1.2 merge commit](https://github.com/kontena/kontena/commit/b80063e88912c2f62d119e5b58352c6e09add0b9)
* [v1.2.0 changes](https://github.com/kontena/kontena/compare/v1.2.0...release/v1.2.1.rc1)

### CODE REVIEW

**Comment by SpComb** [comment]
Dunno if the "Known issues" format is that great (the 1.2.1 known issues affect 1.2.0), but I think it makes sense to pick out issues that are used to work in 1.1, but are specifically broken in 1.2, so that users upgrading can take them into account.

**Comment by jakolehm** [comment]
I would list first fixed issues.

**Comment by SpComb** [comment]
e2e specs pass apart from the usual suspects: #2117 #2118

**Comment by SpComb** [comment]
Travis deploy is green

* https://github.com/kontena/kontena/releases/tag/v1.2.1.rc1
* https://travis-ci.org/kontena/kontena/builds/226384067
* https://travis-ci.org/kontena/kontena/jobs/226384072

**Pull request merged**
