### PR TITLE
Activate plugin gem and dependencies before loading the plugin

### PR DESCRIPTION
**Pull request by kke**
Currently the CLI using something like `load '/usr/foofoo/lib/kontena_cli_plugin.rb'` to load plugins.

This will not activate the plugins dependencies correctly. The plugins load paths will not be added to `$LOAD_PATH` and `/usr/foofoo/lib/kontena_cli_plugin.rb` will not be added to `$LOADED_FEATURES`.

This PR makes plugin_manager activate the plugin gem and its' dependencies before requiring (instead of loading) the `kontena_cli_plugin.rb`.

With `DEBUG=plugin` you get a bit more detailed report of what was loaded and added to load paths.

Also added "shell" to  the "you have not installed plugin X" notification thing.

Related reading: http://erik.hollensbe.org/2013/05/11/gem-activation-and-you/

### CODE REVIEW

**Comment by SpComb** [comment]
How have the plugin dependencies been working so far without this fix? The `require` has just loaded the most recent version of whatever gem, ignoring the versioned dependencies in the plugin gemfiles?

This seems to introduce some incompatibilities with some of the existing plugin dependency versions? Presumably because they were just ignored before?

**Comment by kke** [comment]
Plugins were loaded with `load` instead of require. 

Also it's (still) loading the `kontena_cli_plugin.rb` using a complete path, so no gems get activated.

If the plugin had a file such as `lib/kontena-plugin-aws.rb` and plugin_manager was simply doing `require 'kontena-plugin-aws'`, rubygems would handle the activation and load path setting automatically.

**Comment by SpComb** [comment]
> Also it's (still) loading the kontena_cli_plugin.rb using a complete path, so no gems get activated.
> 
> If the plugin had a file such as lib/kontena-plugin-aws.rb and plugin_manager was simply doing require 'kontena-plugin-aws', rubygems would handle the activation and load path setting automatically.

Is the new `spec.activate` `spec.activate_dependencies` equivalent to what happens when you do `require 'kontena-plugin-aws'` using the automatic gem activation?

**Comment by kke** [comment]
With `load(plugin)` and no `activate`/`activate_dependencies` in plugin_manager.rb as it was before this PR:

```
Loading plugin kontena-plugin-packet
Plugin manager loaded features for kontena-plugin-packet:
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/token_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/project_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/type_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/facility_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/master/create_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/master_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/nodes/create_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/nodes/restart_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/nodes/terminate_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/node_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet_command.rb

No load paths added
```

With this PR:
```
Activating plugin kontena-plugin-packet
Loading plugin kontena-plugin-packet
Plugin manager loaded features for kontena-plugin-packet:
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/token_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/project_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/type_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/facility_option.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/master/create_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/master_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/nodes/create_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/nodes/restart_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/nodes/terminate_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet/node_command.rb
- /usr/local/Cellar/rbenv/1.1.0/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena/plugin/packet_command.rb
- /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib/kontena_cli_plugin.rb

Plugin manager load paths added for kontena-plugin-packet:
- /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.2/lib
- /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib
- /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.11.0.1/lib
- /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/packethost-0.0.8/lib
- /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/kontena-plugin-packet-0.2.5/lib
```

**Comment by kke** [comment]
to clarify:

`$LOADED_FEATURES` is an array of full paths to all required files 
`$LOAD_PATH` is just like $PATH in shell that is used when you do something like `require 'foofoo'`, it will go through them in order and loads the first `foofoo` it spots.

**Comment by SpComb** [comment]
Bumping this to 1.2.1, because it doesn't seem like a regression over 1.1, nor does it fix any issue blocking a 1.2.0 release, and it's something we can fix later?

**Comment by SpComb** [comment]
Needs merge per #2184.

**Pull request merged**
