### PR TITLE
Allow BYOLB by setting KONTENA_SERVICE_ROLE=lb env var

### PR DESCRIPTION
**Pull request by jakolehm**
Bring Your Own Load Balancer

```
custom-lb:
  image: my/lb:latest
  environment:
    - KONTENA_SERVICE_ROLE=lb
```

### CODE REVIEW

**Comment by jakolehm** [comment]
@nevalla @miskun ping

**Comment by jakolehm** [comment]
Related #389

**Comment by nevalla** [comment]
LGTM!

**Comment by hans-d** [comment]
:+1:

**Pull request merged**
