### PR TITLE
Rest api docs

### PR DESCRIPTION
**Pull request by jakolehm**
Rest api docs are generated with [Slate](https://github.com/lord/slate/).

Layout:
screen shot 2016-11-26 at 08 57 32

### CODE REVIEW

**Comment by jnummelin** [comment]
Looks really nice already! :)

**Comment by jakolehm** [comment]
@jnummelin I think we can merge this?

**Comment by jakolehm** [comment]
Let's do a separate pr for linking this to actual docs...

**Comment by jnummelin** [comment]
Sure. I was kinda waiting for the WIP flag to go away :)

**Pull request merged**
