### PR TITLE
Fix stopped services with open deploys blocking deploy queue

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Comment by jnummelin** [comment]
This means now that when user tries to deploy a stopped service the deploy is just silently dropped. Is that really OK or are users expecting that deploying a stopped service actually deploys AND starts it?

**Comment by jakolehm** [comment]
Good point. User expects deploy to change service state because that's how it has been working in the past.

**Comment by jakolehm** [comment]
Improved deploy mutation logic a bit. 

/cc @nevalla

**Comment by nevalla** [comment]
LGTM

**Comment by jnummelin** [comment]
👍

**Pull request merged**
