### PR TITLE
Block calls to Weave#start via #on_node_info

### LINKED ISSUE #1530: Multiple node_info calls to agent might trigger weave setup error
Logs from the crime scene: https://gist.github.com/jakolehm/72ed5feca99f8a90e7fccc4b1fc05a93

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1530

### CODE REVIEW

**Comment by SpComb** [comment]
```
kontena-agent | D, [2016-12-12T13:45:53.351667 #1] DEBUG -- NetworkAdapters::WeaveExecutor: weaveexec ok: ["--local", "expose", "ip:10.81.0.1/16"]
kontena-agent | 10.81.0.1
kontena-agent | 
kontena-agent | I, [2016-12-12T13:45:53.358746 #1]  INFO -- Kontena::NetworkAdapters::Weave: Exposed host node at cidr=10.81.0.1/16
kontena-agent | E, [2016-12-12T13:45:53.358873 #1] ERROR -- Kontena::NetworkAdapters::Weave: RuntimeError: Cannot execute blocks on sender in exclusive mode
kontena-agent | D, [2016-12-12T13:45:53.358946 #1] DEBUG -- NetworkAdapters::Weave: /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:13:in `initialize'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:8:in `initialize'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:20:in `new'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:20:in `method_missing'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:195:in `ensure_exposed'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:271:in `post_start'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:242:in `start'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:172:in `block in on_node_info'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:171:in `on_node_info'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'

```

**Comment by jakolehm** [comment]
@SpComb removed exclusive and added plain-old-wait. Kinda should work but we cannot guarantee order of start calls (not sure how critical that is in this case)

**Comment by SpComb** [comment]
Tested with some `5.times do Celluloid::Notifications.publish('agent:node_info', data)` and it seems better than the current state. I suppose with Celluloids concurrency model the `@starting` logic might even be concurrency-safe?

OTOH I think order does matter, if things like the `info['peer_ips']` change from public -> private as the node labels are updated. However, the current implementation doesn't preserve ordering either, so I guess this is still an improvement as-is..

**Comment by jakolehm** [comment]
Just thinking if wait should be inside the `#start`method.. ?

**Comment by SpComb** [comment]
> Just thinking if wait should be inside the #startmethod.. ?

I suppose you could event combine it with the `images_exist?`, it shouldn't make any difference, `on_node_info` is the only place it's called.

```ruby
def start
    wait { images_exist? && !starting? }
    @starting = true

end

**Comment by jakolehm** [comment]
Refactored, I think it's cleaner now.

**Pull request merged**
