### PR TITLE
Implement kontena master users commands

### PR DESCRIPTION
**Pull request by nevalla**
This PR implements initial `kontena master users` commands:

- `kontena master users invite <email1> <email2> ...`
- `kontena master users add-role <role> <user1> <user2> ...`
- `kontena master users remove-role <role> <user1> <user2> ...`

### CODE REVIEW

**Comment by jakolehm** [comment]
Why `users` instead of `user`?

**Comment by nevalla** [comment]
I chose `users` because commands takes user/email array as parameter (updated to description). @miskun any opinions?

**Comment by miskun** [comment]
I'm always happy to see plural :) :+1:

**Comment by jakolehm** [comment]
:+1:

**Pull request merged**
