### PR TITLE
Info on node initial membership.

### LINKED ISSUE #515: Node details should report if node is part of "initial" cluster (etcd member)

### PR DESCRIPTION
**Pull request by jnummelin**
This PR adds initial membership info on node list:
```
$ bin/kontena node list
Name                                                                   Status     Initial node?   Labels                                  
fragrant-snow-95                                                       online     Yes             -                                       
green-wildflower-24                                                    online     No              -                                       
```

Fixes #515

### CODE REVIEW

**Comment by jakolehm** [comment]
Column name is too long for my taste.. can we come up with something shorter? :)

**Comment by jakolehm** [comment]
And this information should be also visible in node details, right?

**Comment by jnummelin** [comment]
Would just `Initial?` be enough for the column name?

**Comment by jnummelin** [comment]
Better this way?:
```
kontena node list
Name                                                                   Status     Initial    Labels                                  
fragrant-snow-95                                                       offline    yes        -           
```
```
kontena node show fragrant-snow-95
fragrant-snow-95:
  ...
  initial node: yes
  ...
```

**Comment by jakolehm** [comment]
Better 👍

**Pull request merged**
