### PR TITLE
Dynamic load balancing

### PR DESCRIPTION
**Pull request by jakolehm**
This PR adds support for dynamic load balancing. Actual load balancers are haproxy/confd services that watch keys from etcd. Load balancers can be described in `kontena.yml` and services are connected automagically by linking services to load balancer. If balanced service is scaled/re-deployed then load balancer will reload it's configuration on the fly (without dropping connections).

Internet facing load balancer example:

```
internet_lb:
  image: kontena/lb:latest
  ports:
    - 80:80

web:
  image: nginx:latest
  environment:
    - KONTENA_LB_MODE=http
    - KONTENA_LB_BALANCE=roundrobin
    - KONTENA_LB_INTERNAL_PORT=80
    - KONTENA_LB_VIRTUAL_HOSTS=www.kontena.io,kontena.io
  links:
    - internet_lb
api:
  image: registry.kontena.local/restapi:latest
  environment:
    - KONTENA_LB_MODE=http
    - KONTENA_LB_BALANCE=roundrobin
    - KONTENA_LB_INTERNAL_PORT=8080
    - KONTENA_LB_VIRTUAL_PATH=/api
  links:
    - internet_lb
```

Internal tcp load balancer example:
```
galera_lb:
  image: kontena/lb:latest

galera:
  image: registry.kontena.local/galera:latest
  environment:
    - KONTENA_LB_MODE=tcp
    - KONTENA_LB_BALANCE=leastcon
    - KONTENA_LB_EXTERNAL_PORT=3306
    - KONTENA_LB_INTERNAL_PORT=3306
  links:
    - galera_lb
```

### Config Env variables for balanced services
* `KONTENA_LB_MODE`: mode of load balancing, possible values: http (default), tcp
* `KONTENA_LB_BALANCE`: load balancing algorithm to use, possible values are: roundrobin (default), source, leastcon 
* `KONTENA_LB_INTERNAL_PORT`: service port that is attached to load balancer
* `KONTENA_LB_EXTERNAL_PORT`: service port that load balancer starts to listen (only for tcp mode)
* `KONTENA_LB_VIRTUAL_HOSTS`: comma separated list of virtual hosts (only for http mode)
* `KONTENA_LB_VIRTUAL_PATH`: path that is used to match request, example "/api" (only for http mode)
* `KONTENA_LB_CUSTOM_SETTINGS`: extra settings, each line will be appended to either related backend section or listen session in the HAProxy configuration file

### Config env variables for load balancer
* `SSL_CERTS`: one or more ssl certificates that are used to terminate ssl connections, first certificate is used as default

### CODE REVIEW

**Comment by nevalla** [comment]
Looks good!

**Comment by miskun** [comment]
yes, looking good. could add short description about supported values for:
* KONTENA_LB_MODE
* KONTENA_LB_BALANCE

**Comment by jakolehm** [comment]
Updated description to include supported env variables

**Comment by miskun** [comment]
Nice! I think it's good now!

**Pull request merged**
