### PR TITLE
Sort initializers while loading, load symmetric-encryption before seed

### LINKED ISSUE #1277: Server start order issue
There seems to be a start order issue where `/app/app/initializers/symetric_encryption.rb` is not initialised before its been used in `/app/app/initializers/00_seed.rb`

```
[1] Puma starting in cluster mode...
[1] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
[1] * Min threads: 8, max threads: 8
[1] * Environment: production
[1] * Process workers: 1
[1] * Phased restart available
[1] * Listening on tcp://0.0.0.0:9292
[1] Use Ctrl-C to stop
[6] + Gemfile in context: /app/Gemfile
/usr/lib/ruby/gems/2.3.0/gems/symmetric-encryption-3.8.2/lib/symmetric_encryption/symmetric_encryption.rb:109:in `decrypt': Call SymmetricEncryption.load! or SymmetricEncryption.cipher= prior to encrypting or decrypting data (SymmetricEncryption::ConfigError)
	from /app/app/models/configuration.rb:37:in `decrypt'
	from /app/app/models/configuration.rb:59:in `get'
	from /app/app/models/configuration.rb:17:in `block in seed'
	from /app/app/models/configuration.rb:16:in `each'
	from /app/app/models/configuration.rb:16:in `seed'
	from /app/app/initializers/00_seed.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /app/app/boot.rb:20:in `block in <top (required)>'
	from /app/app/boot.rb:20:in `each'
	from /app/app/boot.rb:20:in `<top (required)>'
	from config/puma.rb:5:in `require_relative'
	from config/puma.rb:5:in `block in _load_from'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:426:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	from /usr/bin/puma:23:in `load'
	from /usr/bin/puma:23:in `<main>'
```

I think a rename might just fix this.

### PR DESCRIPTION
**Pull request by kke**
Fixes #1277

### CODE REVIEW

**Comment by SpComb** [comment]
Please also sort `mongoid` before `01_seed.rb`, so that it doesn't need the `require_relative` to bypass the ordering.

**Comment by SpComb** [comment]
There's also the existing `require_relative 'mongoid'` in `mongo_pubsub.rb`. It's probably a harmless no-op at this point, and we can just leave the `mongo_pubsub` initializer unordered?

**Comment by SpComb** [comment]
Yeah, it was broken before

```
/home/kontena/kontena/kontena/server/app/initializers/mongo_pubsub.rb:1:in `require_relative': cannot load such file -- /home/kontena/kontena/kontena/server/app/initializers/mongoid (LoadError)
	from /home/kontena/kontena/kontena/server/app/initializers/mongo_pubsub.rb:1:in `<top (required)>'
	from /home/kontena/kontena/kontena/server/app/boot.rb:22:in `require'
	from /home/kontena/kontena/kontena/server/app/boot.rb:22:in `block in <top (required)>'
	from /home/kontena/kontena/kontena/server/app/boot.rb:20:in `each'
	from /home/kontena/kontena/kontena/server/app/boot.rb:20:in `<top (required)>'
	from config/puma.rb:5:in `require_relative'
	from config/puma.rb:5:in `block in _load_from'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:426:in `run'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/bin/puma:23:in `load'
	from /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/bin/puma:23:in `<main>'
```

**Comment by SpComb** [comment]
LGTM

With some extra logging:
```
[9478] Puma starting in cluster mode...
[9478] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
[9478] * Min threads: 8, max threads: 8
[9478] * Environment: development
[9478] * Process workers: 1
[9478] * Phased restart available
[9478] * Listening on tcp://0.0.0.0:9292
[9478] Use Ctrl-C to stop
/home/kontena/kontena/kontena/server/app/initializers/00_mongoid.rb...
/home/kontena/kontena/kontena/server/app/initializers/01_symmetric_encryption.rb...
/home/kontena/kontena/kontena/server/app/initializers/01_symmetric_encryption.rb configure SymmetricEncryption.cipher
/home/kontena/kontena/kontena/server/app/initializers/02_configuration_seed.rb...
/home/kontena/kontena/kontena/server/app/models/configuration.rb Configuration#decrypt oauth2.client_secret: ...
/home/kontena/kontena/kontena/server/app/initializers/authority.rb...
/home/kontena/kontena/kontena/server/app/initializers/celluloid.rb...
/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb...
/home/kontena/kontena/kontena/server/app/initializers/mongo_pubsub.rb...
/home/kontena/kontena/kontena/server/app/initializers/rack_attack.rb...
/home/kontena/kontena/kontena/server/app/initializers/rollbar.rb...
I, [2016-11-03T11:10:43.014370 #9481]  INFO -- ContainerCleanupJob: starting to cleanup stale containers
I, [2016-11-03T11:10:43.015330 #9481]  INFO -- DistributedLockCleanupJob: starting to cleanup stale locks
I, [2016-11-03T11:10:43.016775 #9481]  INFO -- MongoPubsub: starting to tail collection
I, [2016-11-03T11:10:43.017374 #9481]  INFO -- NodeCleanupJob: starting to cleanup stale connections
I, [2016-11-03T11:10:43.017663 #9481]  INFO -- NodeCleanupJob: starting to cleanup stale nodes
I, [2016-11-03T11:10:43.020573 #9481]  INFO -- ServiceBalancerJob: starting to watch services
I, [2016-11-03T11:10:43.021590 #9481]  INFO -- LeaderElectorJob: participating leader elections
I, [2016-11-03T11:10:43.037483 #9481]  INFO -- LeaderElectorJob: won election ♚
[9478] - Worker 0 (pid: 9481) booted, phase: 0

```

**Comment by jakolehm** [comment]
LGTM!

**Pull request merged**
