### PR TITLE
Logo proposal for 1.0

### PR DESCRIPTION
**Pull request by matti**
Since the Kontena 1.0 is nearing, I'm suggesting that the currently very rounded ascii logo is revamped with something like this.

Features include: 
- 3 lines of height (more suitable for displaying in various places because it takes less screen estate) (the current one is 5 lines)
- 3D looks
- Great for t-shirts and hoodies
- Less characters 
- Street credibility

kontena_ _git_add_-p_ _git_ _perl_ _git_add_-p_ _208x58
asdf

### CODE REVIEW

**Comment by miskun** [comment]
Nice!

**Comment by aom** [comment]
Cool! Transparent png with Monaco font:

kontena-v1-logo

Sketch, SVG and friends in zip.

[kontena-v1-logo.zip](https://github.com/kontena/kontena/files/514208/kontena-v1-logo.zip)

**Comment by aom** [comment]
omat_tuotteeni_i_spreadshirt

**Comment by miskun** [comment]
Sweet! Now we have several good candidates for 1.0. Let's figure out a way how to choose the best one :)

**Comment by aom** [comment]
@miskun My bad! Actually it's @matti's logo with transparent bitmaps and scalable vectors 😎

**Comment by saana-kontenacm** [comment]
Hi Matti, thanks for your submission. Unfortunately it wasn't chosen this time. We appreciate you taking the time and effort to design and submit your design though.

**Pull request closed without merging**
