### PR TITLE
Cli: Added functionality to auto-complete services from another configuration file

### PR DESCRIPTION
**Pull request by janivihervas**
Enabled auto-complete of services from another configuration files for `kontena app <sub-command> -f <configuration-file.yml>`and `kontena app <sub-command> --file <configuration-file.yml>` commands. Auto-complete current directory's entries when completing the `-f` or `--file` option.

Implements [#683](https://github.com/kontena/kontena/issues/683).

### CODE REVIEW

**Comment by nevalla** [comment]
Nice addition! We added support to read services from YAML v2 and due to that this PR has some conflicts. Could you rebase and resolve conflicts?

**Comment by janivihervas** [comment]
Sure! I should have time to do it at the end of the week.

**Comment by SpComb** [comment]
Thanks for the contribution, but closing as this seems to have stagnated and is now out of date. Please re-open if you want to update this for Kontena 1.2.

OTOH the `kontena app` commands are less used these days, and the new `kontena stack` services will be completed naturally as part of the `kontena service ..` commands. I think `kontena stack build` is the only command that takes a service name... that would need to be completed in a similar way.

**Comment by janivihervas** [comment]
That's OK :+1:

**Pull request closed without merging**
